/**
 * 
 */
package org.activiti.designer.integration.palette;

/**
 * Entries in the default palette.
 * 
 * @author Tiese Barrell
 * @since 0.5.1
 * @version 1
 * 
 */
public enum PaletteEntry {

	ALL, START_EVENT, TIMER_START_EVENT, ERROR_START_EVENT, ALFRESCO_START_EVENT, END_EVENT, ERROR_END_EVENT, EXCLUSIVE_GATEWAY, INCLUSIVE_GATEWAY, MAIL_TASK, MANUAL_TASK, 
	RECEIVE_TASK, PARALLEL_GATEWAY, SCRIPT_TASK, SERVICE_TASK, CALL_ACTIVITY, SUBPROCESS, EVENT_SUBPROCESS,
	USER_TASK, ALFRESCO_USER_TASK, BOUNDARY_TIMER, BOUNDARY_SIGNAL, BUSINESSRULE_TASK, ALFRESCO_SCRIPT_TASK, ALFRESCO_MAIL_TASK;

}
